### ISSUE TITLE
5 CI/CDについて

### ISSUE THREAD

**Issue by KumakuraHaruto** [cnc4e/cloudnative-practice#46]
■ issue20について2点気になった部分があります。
① mainブランチとマージしないとActions画面に「Self-hosted Runner Test」が表示されなかったので、
マージすることを記載した方がよいと思います。

② issue 19の下記ファイルでhelmコマンドをインストールする。
```
githubConfigUrl: https://github.com/ORG/REPO
githubConfigSecret: pre-defined-secret
template:
  spec:
    serviceAccountName: arc-runner
```
上記のファイルでインストールするとissue 20で動作確認する際、ServiceAccoutのarc-runnerがまだ作成されていないので、
実行Podが立ち上がらずに動作エラーとなりました。
issue 19時点ではServiceAccout部分をコメントアウトすると正常に動作した。
